# Generated by Django 3.1.7 on 2021-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('card_number', models.BigIntegerField(unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('account_name', models.CharField(max_length=256)),
            ],
            options={
                'unique_together': {('user_id', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField()),
                ('account_balance', models.BigIntegerField()),
                ('operation', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation_index', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('account_id', 'operation_index')},
                'index_together': {('account_id', 'created_at')},
            },
        ),
    ]
